version: '3.8'

services:
  client-apps:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
